### ISSUE TITLE
Change name in NPM

### ISSUE THREAD

**Issue by yiss** [rodgc/ngx-feather-icons#1]
When trying to install it from NPM using `npm install --save  ngx-feather-icons` I get :
`npm ERR! code E404
npm ERR! 404 Not Found: ngx-feather-icons@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Applications\npm-cache\_logs\2018-03-16T16_11_31_830Z-debug.log`

so I tried `npm install --save  ngx-feather-icon` and it work, so you need to change the name in the descreption :)

**Comment by rodgc** [comment]
Thx @yiss
